[project]
name = "satguard-protocol"
description = "Bitcoin-backed micro-insurance protocol"
authors = ["SatGuard Team"]
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.insurance-pool]
path = "contracts/insurance-pool.clar"
clarity_version = 2
epoch = 2.5
